name: 🧹 Lint

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-codebase:
    name: Lint codebase
    uses: equinor/ops-actions/.github/workflows/super-linter.yml@21ca4ff773cab0ffe4f4e8e9b2d04c392c075a5e
    permissions:
      contents: read
      statuses: write
    with:
      filter_regex_exclude: (.*CHANGELOG\.md$|docs/workflows/.*)

  lint-pr:
    name: Lint PR
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@21ca4ff773cab0ffe4f4e8e9b2d04c392c075a5e
    permissions:
      contents: read
    with:
      message: ${{ github.event.pull_request.title }}
