name: 🧹 Lint

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: {}

jobs:
  lint-codebase:
    name: Lint codebase
    uses: equinor/ops-actions/.github/workflows/super-linter.yml@f3943374c9677ff00822cb04f0757933b1bc4926
    permissions:
      contents: read
      statuses: write
    with:
      filter_regex_exclude: (.*CHANGELOG\.md$|docs/workflows/.*)

  lint-pr:
    name: Lint PR
    uses: equinor/ops-actions/.github/workflows/commitlint.yml@f3943374c9677ff00822cb04f0757933b1bc4926
    permissions:
      contents: read
    with:
      message: ${{ github.event.pull_request.title }}
